ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Controllers/HandicraftDealersController.cs
using ExotikaTrial2.DataAccess.Repository.IRepository;
using ExotikaTrial2.Models;
using ExotikaTrial2.Models.ViewModels;
using ExotikaTrial2.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ExotikaTrial2.Areas.UserSpecific.Controllers
{
    [Area("UserSpecific"), Authorize(Roles = SD.Role_User_HandicraftDealer)]
    public class HandicraftDealersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public HandicraftDealersController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult HandicraftDealerDashboard()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var statistics = new UserStatsVM()
            {
                visitors = _unitOfWork.Product.GetAll(u => u.HandicraftDealerId == claim.Value).Count(),
                registrations = _unitOfWork.Feedback.GetAll(u=>u.forId==claim.Value).Count()
            };
            return View(statistics);
        }


        public IActionResult AddProduct()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddProduct(Product product)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            product.lastUpdated = DateTime.Now.Date;
            product.HandicraftDealerId = claim.Value;
            product.HandicraftDealer = _unitOfWork.HandicraftDealer.GetFirstOrDefault(u => u.HandicraftDealerId == claim.Value);
            _unitOfWork.Product.Add(product);
            _unitOfWork.Save();
            TempData["Success"] = "Product added successfully";
            return RedirectToAction(nameof(ProductsList));
        }

        public IActionResult ProductsList()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var pdtList = _unitOfWork.Product.GetAll(u => u.HandicraftDealerId == claim.Value, includeProperties:"HandicraftDealer");
            return View(pdtList);
        }


        public IActionResult ProductDetails(int? pdtId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (pdtId == null)
            {
                TempData["Error"] = "An error occured";
                return NotFound();
            }
            var product = _unitOfWork.Product.GetFirstOrDefault(u => u.ProductId == pdtId && u.HandicraftDealerId == claim.Value);
            if (product == null)
            {
                TempData["Error"] = "An error occured";
                return NotFound();
            }
            return View(product);
        }


        public IActionResult EditProduct(int? pdtId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (pdtId == null)
            {
                TempData["Error"] = "An error occured";
                return NotFound();
            }
            var product = _unitOfWork.Product.GetFirstOrDefault(u => u.ProductId == pdtId && u.HandicraftDealerId == claim.Value);
            if (product == null)
            {
                TempData["Error"] = "An error occured";
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditProduct (Product product)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            product.lastUpdated = DateTime.Now.Date;
            //product.HandicraftDealerId = claim.Value;
            product.HandicraftDealer = _unitOfWork.HandicraftDealer.GetFirstOrDefault(u => u.HandicraftDealerId == claim.Value);
            _unitOfWork.Product.Update(product);
            _unitOfWork.Save();
            TempData["Success"] = "Product updated successfully";
            return RedirectToAction(nameof(ProductsList));

        }


        public IActionResult DeleteProduct(int? pdtId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (pdtId == null)
            {
                TempData["Error"] = "An error occured";
                return NotFound();
            }
            var product = _unitOfWork.Product.GetFirstOrDefault(u => u.ProductId == pdtId && u.HandicraftDealerId == claim.Value);
            if (product == null)
            {
                TempData["Error"] = "An error occured";
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(Product product)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (product.HandicraftDealerId==claim.Value)
            {
                TempData["Error"] = "An error occured";
                return NotFound();
            }
            _unitOfWork.Product.Remove(product);
            _unitOfWork.Save();
            TempData["Success"] = "Product deleted successfully";
            return RedirectToAction(nameof(ProductsList));
        }
    }
}

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Views/HandicraftDealers/AddProduct.cshtml
@model ExotikaTrial2.Models.Product


<div style="padding: 10vh;">
    <div style="padding: 10vh; background-color:rgb(255,255,255); border: 2px solid rgb(0,0,0); border-radius: 12px;">


        <form method="post" asp-action="AddProduct" enctype="multipart/form-data">
            @*<div class="row">*@
                <div class=" row col-12">
                    <div class="col-12 pb-2 mb-4">
                        <h2 class="text-primary">Add Product</h2>
                        <hr />
                    </div>
                    @*<div asp-validation-summary="All"></div>*@
                    <div class="mb-4 col-6">
                        <label asp-for="ProductName" id="reqName"></label>
                        <input asp-for="ProductName" class="form-control" />
                        <span asp-validation-for="ProductName" class="text-danger"></span>
                    </div>
                    <div class="mb-4 col-6">
                        <label asp-for="Price"></label>
                        <input asp-for="Price" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="mb-4 col-12">
                        <label asp-for="Description"></label>
                        <textarea asp-for="Description" class="form-control" rows="3"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <hr />
                    <div class="col-12 mt-3">
                        <button type="submit" onclick="return ValidateInput()" class="btn1" style="width:150px">Add</button>
                        <a asp-controller="HandicraftDealers" asp-action="ProductsList" class="btn1" style="width:150px">Back to Products List</a>
                    </div>
                </div>
            @*</div>*@
        </form>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Views/HandicraftDealers/DeleteProduct.cshtml
@model ExotikaTrial2.Models.Product

@{
    ViewData["Title"] = "Delete Product";
}

<div style="padding: 10vh;">
    <div style="padding: 10vh; background-color:rgb(255,255,255); border: 2px solid rgb(0,0,0); border-radius: 12px;">
        <h1>Delete Product</h1>
        <div>
            <p><b>Are you sure you want to delete this?</b></p>
            <br /><br />
            <hr />
            <div class="row">
                <div class="mb-5">
                    <h2>@Html.DisplayNameFor(model => model.ProductName)</h2>
                    <p>@Html.DisplayFor(model => model.ProductName)</p>
                </div>
                <div class="mb-5">
                    <h2>@Html.DisplayNameFor(model => model.Description)</h2>
                    <p>@Html.DisplayFor(model => model.Description)</p>
                </div>
                <div class="mb-5">
                    <h2>@Html.DisplayNameFor(model => model.Price)</h2>
                    <p>@Html.DisplayFor(model => model.Price)</p>
                </div>
                <div class="mb-5">
                    <h2>@Html.DisplayNameFor(model => model.lastUpdated)</h2>
                    <p>@Model.lastUpdated.ToLongDateString()</p>
                </div>
            </div>
        </div>
        <br /><br /><hr /><br /><br />
        <form asp-action="DeleteProduct" style="overflow-y: hidden;">
            <input type="hidden" asp-for="ProductId" />
            <input type="submit" value="Delete" class="btn1" style="background-color: rgb(255,0,0);" />
            <a asp-action="ProductsList" class="btn1">Back to Products List</a>
        </form>
    </div>
</div>

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Views/HandicraftDealers/EditProduct.cshtml
@model ExotikaTrial2.Models.Product

@{
    ViewData["Title"] = "Edit Product Details";
}




<div style="padding: 10vh;">
    <div style="padding: 10vh; background-color:rgb(255,255,255); border: 2px solid rgb(0,0,0); border-radius: 12px;">
        <h1>Edit Product Details</h1>
        <hr /><br /><br />
        <form asp-action="EditProduct">
            <input asp-for="ProductId" type="hidden" />
            <input asp-for="HandicraftDealerId" type="hidden" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>@*
            <div class="form-group">
                <label asp-for="DateOfJoining" class="control-label"></label>
                <input asp-for="DateOfJoining" class="form-control" />
                <span asp-validation-for="DateOfJoining" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn1" />
            </div>
        </form>

        <br /><br /><hr /><br /><br />
        <a asp-action="ProductsList" class="btn1">Back to List</a>
    </div>
</div>


@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Views/HandicraftDealers/ProductDetails.cshtml
@model ExotikaTrial2.Models.Product

@{
    ViewData["Title"] = "Product Details";
}


<div style="padding: 10vh;">
    <div style="padding: 10vh; background-color:rgb(255,255,255); border: 2px solid rgb(0,0,0); border-radius: 12px;">
        <h1>Product Details</h1>
        <div>
            <hr /><br><br />
            <div class="row">
                <div class="mb-5">
                    <h2>@Html.DisplayNameFor(model => model.ProductName)</h2>
                    <p>@Html.DisplayFor(model => model.ProductName)</p>
                </div>
                <div class="mb-5">
                    <h2>@Html.DisplayNameFor(model => model.Description)</h2>
                    <p>@Html.DisplayFor(model => model.Description)</p>
                </div>
                <div class="mb-5">
                    <h2>@Html.DisplayNameFor(model => model.Price)</h2>
                    <p>@Html.DisplayFor(model => model.Price)</p>
                </div>@*
                <div class="mb-5">
                    <h2>@Html.DisplayNameFor(model => model.DateOfJoining)</h2>
                    <p>@Html.DisplayFor(model => model.DateOfJoining)</p>
                </div>*@
            </div>
        </div>
            <br /><br /><hr /><br /><br />
            <a asp-action="EditProduct" asp-route-pdtId="@Model?.ProductId" class="btn1" style="width:auto">Edit</a>
            <a asp-action="ProductsList" class="btn1" style="width:auto">Back to Product List</a>
    </div>
</div>