ExotikaTrial2/ExotikaTrial2/Areas/Base/Controllers/BasePagesController.cs
using ExotikaTrial2.DataAccess.Repository.IRepository;
using ExotikaTrial2.Models;
using ExotikaTrial2.Models.ViewModels;
using ExotikaTrial2.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using System.Security.Claims;

namespace ExotikaTrial2.Controllers
{
    [Area("Base")]
    public class BasePagesController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        public BasePagesController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ResortHome()
        {
            return View();
        }

        public IActionResult HandicraftDealerHome()
        {
            return View();
        }

        public IActionResult ResortDetails(string? resortId)
        {
            if (resortId != null)
            {
                ResortDetailsVM resortData = new ResortDetailsVM
                {
                    resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == resortId),
                    packages = _unitOfWork.Package.GetAll(u => u.ResortId == resortId)
                };

                return View(resortData);
            }
            return NotFound();
        }

        public IActionResult ResortsList()
        {
            var resorts = _unitOfWork.Resort.GetAll();
            var handicrafts = _unitOfWork.Product.GetAll(includeProperties: "HandicraftDealer");
            var data = new TouristHomeVM()
            {
                Resorts = resorts,
                Products = handicrafts
            };
            return View(data);
        }

        public IActionResult VendorHome()
        {
            var contracts = _unitOfWork.Requirement.GetAll(u => u.Status == SD.Requirement_Posted, includeProperties: "Resort");
            return View(contracts);
        }

        public IActionResult Book(int? packageId)
        {
            if (packageId == null)
            {
                return NotFound();
            }
            var resId = _unitOfWork.Package.GetFirstOrDefault(u => u.PackageId == packageId).ResortId;
            var res = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == resId);
            var pkg = _unitOfWork.Package.GetFirstOrDefault(u => u.PackageId == packageId);
            var pkgBook = new Booking()
            {
                PackageId = packageId,
                ResortId = resId,
                Resort = res,
                Package = pkg
            };
            return View(pkgBook);
        }

        public IActionResult Proposal(int? requirementId)
        {
            if (requirementId == null)
            {
                return NotFound();
            }
            var resId = _unitOfWork.Requirement.GetFirstOrDefault(u => u.RequirementId == requirementId).ResortId;
            var res = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == resId);
            var req = _unitOfWork.Requirement.GetFirstOrDefault(u => u.RequirementId == requirementId);
            var contProposal = new Contract()
            {
                RequirementId = (int)requirementId,
                //ResortId = resId,
                //Resort = res,
                Requirement = req
            };
            return View(contProposal);
        }


        [HttpPost]
        [Authorize(Roles = SD.Role_User_Vendor)]
        [ValidateAntiForgeryToken]
        public IActionResult Proposal(Contract newContract, IFormFile file)
        {
            if (!User.IsInRole(SD.Role_User_Vendor))
            {
                TempData["Error"] = "Please Login to your account to continue";
            }
            if (ModelState.IsValid && User.IsInRole(SD.Role_User_Vendor))
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"proposalFiles");
                    var extension = Path.GetExtension(file.FileName);
                    using (var fileStreams = new FileStream(Path.Combine(uploads, filename + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    newContract.ProposalFile = @"\proposalFiles\" + filename + extension;
                }
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                newContract.VendorId = claim.Value;
                newContract.Vendor = _unitOfWork.Vendor.GetFirstOrDefault(u => u.VendorId == claim.Value);
                newContract.Requirement = _unitOfWork.Requirement.GetFirstOrDefault(u => u.RequirementId == newContract.RequirementId);
                newContract.CreateDate = DateTime.Now;
                newContract.Status = SD.Proposal_Given;
                newContract.Requirement.Status = SD.Requirement_ProposalsReceived;
                _unitOfWork.Contract.Add(newContract);
                _unitOfWork.Save();
                TempData["Success"] = "Proposal sent successfully";
                return RedirectToAction(nameof(VendorHome));
            }
            TempData["Error"] = "An error occured. Please try later!";
            return View(newContract);
        }


        [HttpPost]
        [ActionName("Book")]
        [Authorize(Roles = SD.Role_User_Tourist)]
        [ValidateAntiForgeryToken]
        public IActionResult Book(Booking newBooking)
        {
            if (!User.IsInRole(SD.Role_User_Tourist))
            {
                TempData["Error"] = "Please Login to your tourist account to continue";
            }
            if (ModelState.IsValid && User.IsInRole(SD.Role_User_Tourist))
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                newBooking.TouristId = claim.Value;
                newBooking.TouristDetails = _unitOfWork.Tourist.GetFirstOrDefault(u => u.TouristId == newBooking.TouristId);
                newBooking.Resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == newBooking.ResortId);
                newBooking.Package = _unitOfWork.Package.GetFirstOrDefault(u => u.PackageId == newBooking.PackageId);
                int duration = (newBooking.CheckOutDate.Date - newBooking.CheckInDate.Date).Days;
                newBooking.TotalPrice = (newBooking.Package.Price * newBooking.noOfBookings * duration);
                _unitOfWork.Bookings.Add(newBooking);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Book_Summary), new { bookingId = newBooking.BookingID });
            }
            return View(newBooking);
        }


        [Authorize(Roles = SD.Role_User_Tourist)]
        public IActionResult Book_Summary(int? bookingId)
        {
            Booking book = _unitOfWork.Bookings.GetFirstOrDefault(u => u.BookingID == bookingId, includeProperties: "Package,Resort,TouristDetails");
            return View(book);
        }


        [HttpPost]
        [ActionName("Book_Summary")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = SD.Role_User_Tourist)]
        public IActionResult Book_Payment(int? bookingId)
        {
            if (!User.IsInRole(SD.Role_User_Tourist))
            {
                TempData["Error"] = "Please Login to your account to continue";
            }
            Booking book = _unitOfWork.Bookings.GetFirstOrDefault(u => u.BookingID == bookingId, includeProperties: "Package,Resort,TouristDetails");
            ResortBookings bookFinal = new()
            {
                PackageId = book.PackageId,
                Package = book.Package,
                ResortId = book.ResortId,
                Resort = book.Resort,
                TouristId = book.ResortId,
                TouristDetails = book.TouristDetails,
                TotalPrice = book.TotalPrice,
                idType = book.idType,
                idNumber = book.idNumber,
                CheckInDate = book.CheckInDate,
                CheckOutDate = book.CheckOutDate,
                noOfBookings = book.noOfBookings,
                CreateDate = DateTime.Now

            };
            int duration = (bookFinal.CheckOutDate.Date - bookFinal.CheckInDate.Date).Days;
            // Stripe Settings
            var domain = "https://localhost:44378/";
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>
                    {
                        new SessionLineItemOptions
                            {
                                PriceData = new SessionLineItemPriceDataOptions
                                    {
                                        UnitAmount = (long)book.TotalPrice*100,
                                        Currency = "inr",
                                        ProductData = new SessionLineItemPriceDataProductDataOptions
                                            {
                                                Name = bookFinal.Package.Name,
                                            },
                                    },
                                Quantity = 1,
                            },
                    },
                Mode = "payment",
                SuccessUrl = domain + $"Base/BasePages/PaymentConfirmation?bookingId={bookFinal.BookingID}",
                CancelUrl = domain + $"Base/BasePages/Book_Summary?bookingId={bookFinal.BookingID}",
            };

            var service = new SessionService();

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Controllers/AdminController.cs
using ExotikaTrial2.DataAccess.Repository.IRepository;
using ExotikaTrial2.Models.ViewModels;
using ExotikaTrial2.Utility;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ExotikaTrial2.Areas.UserSpecific.Controllers
{
    [Area("UserSpecific")]
    public class AdminController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AdminController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            StatsVM s = new StatsVM ()
            {
                tourist = _unitOfWork.Tourist.GetAll().Count(),
                resort = _unitOfWork.Resort.GetAll().Count(),
                vendor = _unitOfWork.Vendor.GetAll().Count(),
                handicraftDealer = _unitOfWork.HandicraftDealer.GetAll().Count(),
            };
            return View(s);
        }

        public IActionResult TouristStats()
        {
            UserStatsVM touristStats = new UserStatsVM()
            {
                visitors = 0,
                registrations = _unitOfWork.Tourist.GetAll().Count(),
                bookings = _unitOfWork.ResortBooking.GetAll().Count()
            };
            return View(touristStats);
        }

        public IActionResult ResortStats()
        {
            UserStatsVM resortStats = new UserStatsVM()
            {
                visitors = 0,
                registrations = _unitOfWork.Tourist.GetAll().Count(),
                bookings = _unitOfWork.ResortBooking.GetAll().Count()
            };
            return View(resortStats);
        }

        public IActionResult VendorStats()
        {
            UserStatsVM vendorStats = new UserStatsVM()
            {
                visitors = 0,
                registrations = _unitOfWork.Tourist.GetAll().Count(),
                bookings = _unitOfWork.ResortBooking.GetAll().Count()
            };
            return View(vendorStats);
        }

        public IActionResult HandicraftDealerStats()
        {
            UserStatsVM handicraftDealerStats = new UserStatsVM()
            {
                visitors = 0,
                registrations = _unitOfWork.Tourist.GetAll().Count(),
                bookings = _unitOfWork.ResortBooking.GetAll().Count()
            };
            return View(handicraftDealerStats);
        }
    }
}

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Controllers/ResortsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExotikaTrial2.Data;
using ExotikaTrial2.DataAccess.Repository.IRepository;
using ExotikaTrial2.Models;
using Microsoft.AspNetCore.Authorization;
using ExotikaTrial2.Utility;
using ExotikaTrial2.Models.ViewModels;
using System.Security.Claims;

namespace ExotikaTrial2.Controllers
{
    [Area("UserSpecific")]
    [Authorize(Roles = SD.Role_User_Resort)]
    public class ResortsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ResortsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult ResortOwnerDashboard()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var stats = new UserStatsVM()
            {
                registrations = _unitOfWork.ResortBooking.GetAll(u => u.ResortId == claim.Value).Count(),
            };
            return View(stats);
        }

        public IActionResult UpsertFeedback(string? forId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var fbk = _unitOfWork.Feedback.GetFirstOrDefault(u => u.forId == forId && u.byId == claim.Value, includeProperties: "vendor,resort");
            Feedback feedback = new();
            if (fbk == null)
            {
                feedback.forId = forId;
                feedback.byId = claim.Value;
                feedback.resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == claim.Value);
                feedback.vendor = _unitOfWork.Vendor.GetFirstOrDefault(u => u.VendorId == forId);
                return View(feedback);
            }
            else return View(fbk);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpsertFeedback(Feedback feedback)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (ModelState.IsValid)
            {
                if (feedback.Id == 0)
                {
                    feedback.lastUpdated = DateTime.Now;
                    feedback.resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == feedback.byId);
                    feedback.vendor = _unitOfWork.Vendor.GetFirstOrDefault(u => u.VendorId == feedback.forId);
                    _unitOfWork.Feedback.Add(feedback);
                    _unitOfWork.Save();
                    TempData["Success"] = "Feedback Posted Successfully!";
                }
                else
                {
                    if (feedback.byId == claim.Value)
                    {
                        feedback.lastUpdated = DateTime.Now;
                        feedback.resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == feedback.byId);
                        feedback.vendor = _unitOfWork.Vendor.GetFirstOrDefault(u => u.VendorId == feedback.forId);
                        _unitOfWork.Feedback.Update(feedback);
                        _unitOfWork.Save();
                        TempData["Success"] = "Feedback Updated Successfully!";
                    }
                }
                return RedirectToAction("OngoingContracts", "Requirements");   //return RedirectToAction("Index", "ControllerName"); if we want to go to some other controller
            }
            TempData["Error"] = "An error occured. Please try later.";
            return View(feedback);
        }



        public IActionResult TouristFeedbacks()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var feedbackList = _unitOfWork.Feedback.GetAll(u => u.forId == claim.Value, includeProperties: "tourist,resort");
            if (feedbackList == null)
            {
                return NotFound();
            }
            return View(feedbackList);
        }

    }
}

ExotikaTrial2/ExotikaTrial2/Views/Shared/_DashboardLayout.cshtml
@using ExotikaTrial2.Utility
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>User Dashboard | Exotika</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="!/images/Logo.png" type="image/png">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="~/CSS/Style.css" runat="server" />
    <link rel="stylesheet" href="~/CSS/DashboardCSS.css" runat="server" />
    <link rel="stylesheet" href="~/CSS/FormCSS.css" runat="server" />
    <link rel="stylesheet" href="~/CSS/bootswatch.css" runat="server" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <style>
        .BlurBg {
            filter: blur(5px);
        }

        #Table, #EditDetails {
            margin: 20vh auto;
            padding: 5vh 10vh;
            width: 85%;
            background: rgb(255,255,255);
            border: 2px solid rgb(0,0,0);
            border-radius: 10px;
            text-align: justify;
        }

        #FilterBy {
            margin-top: 2.5vh;
            width: 90%;
            margin-left: 5%;
            padding: 2vh;
            border: 2px solid rgb(0,0,0);
            border-radius: 10px;
            font-size: 110%;
            margin-bottom: 20px;
        }

        #Table, #Table tr td, #Table tr th {
            border: 2px solid rgb(0,0,0);
            border-collapse: collapse;
            padding: 10px;
            text-align: center;
        }

            #Table tr th {
                background: rgba(0,0,0, 0.1);
            }

        #EditDetails {
            position: absolute;
            top: 0;
            margin-left: 6vw;
            display: none;
        }

            #EditDetails label {
                float: left;
                margin-top: 5vh;
            }

            .btn, #EditDetails input {
                margin-top: 2.5vh;
                width: 95%;
                margin-left: 5%;
                padding: 2vh;
                border: 2px solid rgb(0,0,0);
                border-radius: 10px;
                font-size: 110%;
            }

                .btn, #EditDetails input[type=submit], #EditDetails input[type=reset] {
                    width: auto;
                    margin-left: 0;
                    margin-top: 5%;
                    cursor: pointer;
                    transition-duration: 0.5s;
                    margin-right: 20px;
                }

        .btn {
            font-size: 90%;
            padding: 0 1px;
            border: 1px solid rgb(0,0,0);
            width: 45%;
            margin-right: 0;
        }

            .btn:hover, #EditDetails input[type=submit]:hover, #EditDetails input[type=reset]:hover {
                background-color: rgb(0,146,106);
                color: rgb(255,255,255);
            }

        dt {
            font-weight: 900;
            margin-top: 5vh;
        }

        dd {
            margin-left: 5vh;
        }
    </style>
</head>


<body>
    <div class="sidebar">
        <div class="logo-details">
            <img src="~/Images/Exotika.png" id="logo-img" alt="Exotika" />
            @if (User.IsInRole(SD.Role_User_Tourist))
            {
                <a id="logo-name" asp-area="Base" asp-controller="BasePages" asp-action="ResortsList" target="_blank">Exotika</a>
            }
            else
            {
                if (User.IsInRole(SD.Role_User_Vendor))
                {
                    <a id="logo-name" asp-area="Base" asp-controller="BasePages" asp-action="VendorHome" target="_blank">Exotika</a>
                }
            }
        </div>
        <br>
        <ul class="nav-links">
            @if (User.IsInRole(SD.Role_User_Resort))
            {
                <li><a asp-area="UserSpecific" asp-controller="Resorts" asp-action="ResortOwnerDashboard"><i class='bx bx-grid-alt'></i><span class="links_name">Statistics</span></a></li>
                <li><a asp-area="Identity" asp-page="/Account/Manage/Index"><i class='bx bxs-contact'></i><span class="links_name">Manage Account</span></a></li>
                <li><a asp-area="UserSpecific" asp-controller="Requirements" asp-action="RequirementsList"><i class='bx bxs-data'></i><span class="links_name">Requirements</span></a></li>
                <li><a asp-area="UserSpecific" asp-controller="Requirements" asp-action="OngoingContracts"><i class='bx bxs-data'></i><span class="links_name">Ongoing Contracts</span></a></li>
                <li><a asp-area="UserSpecific" asp-controller="Employees" asp-action="Index"><i class='bx bx-cart-alt'></i><span class="links_name">Empoyee Logistics</span></a></li>
                <li><a asp-area="UserSpecific" asp-controller="Packages" asp-action="Index"><i class='bx bx-paint'></i><span class="links_name">Packages Available</span></a></li>
                <li><a asp-area="UserSpecific" asp-controller="Resorts" asp-action="TouristFeedbacks"><i class='bx bx-message'></i><span class="links_name">Feedbacks</span></a></li>
                @*<li class="log_out"><a href="SignIn.html"><i class='bx bx-log-out'></i><span class="links_name">Log out</span></a></li>*@
            }
            else
            {
                if (User.IsInRole(SD.Role_User_Tourist))
                {
                    <li><a asp-area="Identity" asp-page="/Account/Manage/Index"><i class='bx bxs-contact'></i><span class="links_name">Manage Account</span></a></li>
                    @*<li><a asp-area="UserSpecific" asp-controller="Tourists" asp-action="Index"><i class='bx bxs-contact'></i><span class="links_name">Tourist  Details</span></a></li>*@
                    <li><a asp-area="UserSpecific" asp-controller="Tourists" asp-action="BookingHistory"><i class='bx bxs-data'></i><span class="links_name">Booking History</span></a></li>
                    <li><a asp-area="UserSpecific" asp-controller="Tourists" asp-action="Feedbacks"><i class='bx bx-message'></i><span class="links_name">Feedbacks</span></a></li>
                }
                else
                {
                    if (User.IsInRole(SD.Role_User_Vendor))
                    {
                        <li><a asp-area="UserSpecific" asp-controller="Vendors" asp-action="VendorDashboard"><i class='bx bx-grid-alt'></i><span class="links_name">Statistics</span></a></li>
                        <li><a asp-area="Identity" asp-page="/Account/Manage/Index"><i class='bx bxs-contact'></i><span class="links_name">Manage Account</span></a></li>
                        <li><a asp-area="UserSpecific" asp-controller="Vendors" asp-action="ContractList"><i class='bx bxs-contact'></i><span class="links_name">Contracts</span></a></li>
                        <li><a asp-area="UserSpecific" asp-controller="Vendors" asp-action="Feedbacks"><i class='bx bx-message'></i><span class="links_name">Feedbacks</span></a></li>
                    }
                    else
                    {
                        if (User.IsInRole(SD.Role_User_HandicraftDealer))
                        {
                            <li><a asp-area="UserSpecific" asp-controller="HandicraftDealers" asp-action="HandicraftDealerDashboard"><i class='bx bx-grid-alt'></i><span class="links_name">Statistics</span></a></li>
                            <li><a asp-area="Identity" asp-page="/Account/Manage/Index"><i class='bx bxs-contact'></i><span class="links_name">Manage Account</span></a></li>
                            <li><a asp-area="UserSpecific" asp-controller="HandicraftDealers" asp-action="ProductsList"><i class='bx bx-paint'></i><span class="links_name">Products Available</span></a></li>
                            <li><a asp-area="UserSpecific" asp-controller="HandicraftDealers" asp-action="Feedbacks"><i class='bx bx-message'></i><span class="links_name">Feedbacks</span></a></li>
                        }
                        else
                        {
                            if (User.IsInRole(SD.Role_Admin))
                            {
                                <li><a asp-area="UserSpecific" asp-controller="Admin" asp-action="Index"><i class='bx bx-grid-alt'></i><span class="links_name">Dashboard</span></a></li>
                                <li><a asp-area="Identity" asp-page="/Account/Manage/Index"><i class='bx bxs-contact'></i><span class="links_name">Manage Account</span></a></li>
                                <li><a asp-area="UserSpecific" asp-controller="Admin" asp-action="TouristStats"><i class='bx bx-walk'></i><span class="links_name">Tourists</span></a></li>
                                <li><a asp-area="UserSpecific" asp-controller="Admin" asp-action="ResortStats"><i class='bx bx-building-house'></i><span class="links_name">Resorts</span></a></li>
                                <li><a asp-area="UserSpecific" asp-controller="Admin" asp-action="VendorStats"><i class='bx bx-cart-alt'></i><span class="links_name">Vendors</span></a></li>
                                <li><a asp-area="UserSpecific" asp-controller="Admin" asp-action="HandicraftDealerStats"><i class='bx bx-paint'></i><span class="links_name">Handicraft Dealers</span></a></li>
                                <li><a asp-area="UserSpecific" asp-controller="Admin" asp-action="Feedback"><i class='bx bx-message'></i><span class="links_name">Feedbacks</span></a></li>
                                <li><a asp-area="Identity" asp-page="/Account/Register"><i class='bx bx-message'></i><span class="links_name">Register an Account</span></a></li>
                            }
                        }
                    }
                }
            }

            <li class="log_out">
                <a id="logoutForm" class="form-inline log_out" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "BasePages", new { area = "Base" })">
                    <i class="bx bx-logout"></i>
                    <span class="links_name">Logout</span>
                </a>
            </li>
            @*<li class="log_out"><a href="SignIn.html"><i class='bx bx-log-out'></i><span class="links_name">Log out</span></a></li>*@
        </ul>
    </div>

    <section class="registrations">
        <nav>
            <div class="sidebar-button">
                <i class='bx bx-menu sidebarBtn'></i>
                <span class="dashboard">Dashboard</span>
            </div>
            <div class="profile-details">
                <img src="https://img.icons8.com/bubbles/500/000000/test-account.png" alt="" />
                <span class="name">@UserManager.GetUserName(User)</span>
            </div>
        </nav>

        @RenderBody()
        @RenderSection("Scripts", required: false)
    </section>

    @*@RenderBody()
        @RenderSection("Scripts", required: false) *@

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <partial name="_Notification" />
    <script>
        let sidebar = document.querySelector(".sidebar");
        let sidebarBtn = document.querySelector(".sidebarBtn");
        sidebarBtn.onclick = function() {
            sidebar.classList.toggle("active");
            if(sidebar.classList.contains("active")){
                sidebarBtn.classList.replace("bx-menu" ,"bx-menu-alt-right");
                document.getElementById("logo-img").style.width = "75%";
                document.getElementById("logo-name").style.display = "none";
                document.getElementById("logo-img").style.margin = "0 0 0 0.5vw";
            }
            else {
                sidebarBtn.classList.replace("bx-menu-alt-right", "bx-menu");
                document.getElementById("logo-img").style.width = "25%";
                document.getElementById("logo-name").style.display = "inline-block";
                document.getElementById("logo-img").style.margin = "0 2vw 0 1vw";
            }
        }
    </script>
</body>
</html>

ExotikaTrial2/ExotikaTrial2/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}

@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]');
    </script>
}