ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Controllers/RequirementsController.cs
using ExotikaTrial2.DataAccess.Repository.IRepository;
using ExotikaTrial2.Models;
using ExotikaTrial2.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ExotikaTrial2.Areas.UserSpecific.Controllers
{
    [Area("UserSpecific"), Authorize(Roles = SD.Role_User_Resort)]
    public class RequirementsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public RequirementsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult RequirementsList(string status)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var requirementList = _unitOfWork.Requirement.GetAll(u => u.ResortId == claim.Value, includeProperties: "Resort");
            switch (status)
            {
                case "requirementPosted":
                    requirementList = requirementList.Where(u => u.Status == SD.Requirement_Posted);
                    break;
                case "proposalReceived":
                    requirementList = requirementList.Where(u => u.Status == SD.Requirement_ProposalsReceived);
                    break;
                case "proposalAccepted":
                    requirementList = requirementList.Where(u => u.Status == SD.Proposal_Accepted);
                    break;
                default:
                    break;
            }
            return View(requirementList);
        }

        public IActionResult UpsertRequirement(int? requirementId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            Requirement requirement = new();
            if (requirementId == null || requirementId == 0)
            {
                return View(requirement);
            }
            else
            {
                requirement = _unitOfWork.Requirement.GetFirstOrDefault(u => u.RequirementId == requirementId && u.ResortId == claim.Value, includeProperties: "Resort");
                return View(requirement);
            }
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpsertRequirement(Requirement requirement)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (ModelState.IsValid)
            {
                if (requirement.RequirementId == 0)
                {
                    //requirement.lastUpdated = DateTime.Now;
                    // requirement.ResortId = claim.Value;
                    requirement.Resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == claim.Value);
                    requirement.Status = SD.Requirement_Posted;
                    _unitOfWork.Requirement.Add(requirement);
                    TempData["Success"] = "Requirement Details Posted Successfully!";
                }
                else
                {
                    if (requirement.ResortId == claim.Value)
                    {
                        //requirement.lastUpdated = DateTime.Now;
                        requirement.Resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == claim.Value);
                        _unitOfWork.Requirement.Update(requirement);
                        TempData["Success"] = "Requirement Details Updated Successfully!";
                    }
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(RequirementsList));   //return RedirectToAction("Index", "ControllerName"); if we want to go to some other controller
            }
            TempData["Error"] = "An error occured. Please try later.";
            return View(requirement);
        }


        public IActionResult Details(int? requirementId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var requirement = _unitOfWork.Requirement.GetFirstOrDefault(u => u.RequirementId == requirementId && u.ResortId == claim.Value, includeProperties: "Resort");
            return View(requirement);
        }



        public IActionResult Delete(int? requirementId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (requirementId == null || requirementId == 0)
            {
                return NotFound();
            }
            var requirement = _unitOfWork.Requirement.GetFirstOrDefault(u => u.RequirementId == requirementId && u.ResortId == claim.Value, includeProperties: "Resort");
            if (requirement == null)
            {
                return NotFound();
            }
            return View(requirement);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? requirementId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var requirement = _unitOfWork.Requirement.GetFirstOrDefault(u => u.RequirementId == requirementId && u.ResortId == claim.Value, includeProperties: "Resort");
            //var contracts = _unitOfWork.Contract.GetAll(u => u.RequirementId == requirementId && u.Requirement.ResortId == claim.Value, includeProperties: "Requirement,Vendor,Requirement.Resort");
            if (requirement != null)
            {
                _unitOfWork.Requirement.Remove(requirement);
                _unitOfWork.Save();
                TempData["Success"] = "Requirement Deleted Successfully";
                return RedirectToAction(nameof(RequirementsList));
            }
            TempData["Error"] = "An error occured. Please try later.";
            return RedirectToAction(nameof(RequirementsList));
        }

        public IActionResult ProposalList(int? requirementId)
        {
            if (requirementId == null)
            {
                TempData["Error"] = "An error occured. Please try later.";
                return NotFound();
            }
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var proposalList = _unitOfWork.Contract.GetAll(u => u.RequirementId == requirementId && u.Requirement.ResortId == claim.Value, includeProperties: "Requirement,Vendor,Requirement.Resort");
            if (proposalList == null)
            {
                TempData["Error"] = "An error occured. Please try later.";
                return NotFound();
            }
            return View(proposalList);
        }


        public IActionResult ProposalDetails(int? contractId)
        {
            if (contractId == null)
            {
                TempData["Error"] = "An error occured. Please try later.";
                return NotFound();
            }
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var proposal = _unitOfWork.Contract.GetFirstOrDefault(u => u.ContractId == contractId && u.Requirement.ResortId == claim.Value, includeProperties: "Requirement,Vendor,Requirement.Resort");
            if (proposal == null)
            {
                TempData["Error"] = "An error occured. Please try later.";
                return NotFound();
            }
            return View(proposal);
        }

        public IActionResult AcceptProposal(int? contractId)
        {
            if (contractId == null)
            {
                TempData["Error"] = "An error occured. Please try later.";
                return NotFound();
            }
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var proposal = _unitOfWork.Contract.GetFirstOrDefault(u => u.ContractId == contractId && u.Requirement.ResortId == claim.Value, includeProperties: "Requirement,Vendor,Requirement.Resort");
            if (proposal == null)
            {
                TempData["Error"] = "An error occured. Please try later.";
                return NotFound();
            }
            proposal.Requirement.Status = SD.Proposal_Accepted;
            proposal.Status = SD.Proposal_Accepted;
            _unitOfWork.Contract.Update(proposal);
            _unitOfWork.Save();
            TempData["Success"] = "Proposal Accepted!";
            return RedirectToAction(nameof(ProposalDetails), new { contractId = proposal.ContractId });
        }


        public IActionResult OngoingContracts(string type)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var date = DateTime.Now;
            var ongoingContracts = _unitOfWork.Contract.GetAll(u => u.Requirement.ResortId == claim.Value && u.Status == SD.Proposal_Accepted, includeProperties: "Requirement,Vendor,Requirement.Resort");
            switch (type)
            {
                case "products":
                    ongoingContracts = ongoingContracts.Where(u => u.Requirement.Type == "Product");
                    break;
                case "services":
                    ongoingContracts = ongoingContracts.Where(u => u.Requirement.Type == "Service");
                    break;
                default:
                    break;
            }
            return View(ongoingContracts);
        }
    }
}

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Controllers/ResortsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExotikaTrial2.Data;
using ExotikaTrial2.DataAccess.Repository.IRepository;
using ExotikaTrial2.Models;
using Microsoft.AspNetCore.Authorization;
using ExotikaTrial2.Utility;
using ExotikaTrial2.Models.ViewModels;
using System.Security.Claims;

namespace ExotikaTrial2.Controllers
{
    [Area("UserSpecific")]
    [Authorize(Roles = SD.Role_User_Resort)]
    public class ResortsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ResortsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult ResortOwnerDashboard()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var stats = new UserStatsVM()
            {
                registrations = _unitOfWork.ResortBooking.GetAll(u => u.ResortId == claim.Value).Count(),
            };
            return View(stats);
        }

        public IActionResult UpsertFeedback(string? forId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var fbk = _unitOfWork.Feedback.GetFirstOrDefault(u => u.forId == forId && u.byId == claim.Value, includeProperties: "vendor,resort");
            Feedback feedback = new();
            if (fbk == null)
            {
                feedback.forId = forId;
                feedback.byId = claim.Value;
                feedback.resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == claim.Value);
                feedback.vendor = _unitOfWork.Vendor.GetFirstOrDefault(u => u.VendorId == forId);
                return View(feedback);
            }
            else return View(fbk);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpsertFeedback(Feedback feedback)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (ModelState.IsValid)
            {
                if (feedback.Id == 0)
                {
                    feedback.lastUpdated = DateTime.Now;
                    feedback.resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == feedback.byId);
                    feedback.vendor = _unitOfWork.Vendor.GetFirstOrDefault(u => u.VendorId == feedback.forId);
                    _unitOfWork.Feedback.Add(feedback);
                    _unitOfWork.Save();
                    TempData["Success"] = "Feedback Posted Successfully!";
                }
                else
                {
                    if (feedback.byId == claim.Value)
                    {
                        feedback.lastUpdated = DateTime.Now;
                        feedback.resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == feedback.byId);
                        feedback.vendor = _unitOfWork.Vendor.GetFirstOrDefault(u => u.VendorId == feedback.forId);
                        _unitOfWork.Feedback.Update(feedback);
                        _unitOfWork.Save();
                        TempData["Success"] = "Feedback Updated Successfully!";
                    }
                }
                return RedirectToAction("OngoingContracts", "Requirements");   //return RedirectToAction("Index", "ControllerName"); if we want to go to some other controller
            }
            TempData["Error"] = "An error occured. Please try later.";
            return View(feedback);
        }



        public IActionResult TouristFeedbacks()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var feedbackList = _unitOfWork.Feedback.GetAll(u => u.forId == claim.Value, includeProperties: "tourist,resort");
            if (feedbackList == null)
            {
                return NotFound();
            }
            return View(feedbackList);
        }

    }
}

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Controllers/VendorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExotikaTrial2.Data;
using ExotikaTrial2.DataAccess.Repository.IRepository;
using ExotikaTrial2.Models;
using System.Security.Claims;
using ExotikaTrial2.Models.ViewModels;
using ExotikaTrial2.Utility;
using Microsoft.AspNetCore.Authorization;

namespace ExotikaTrial2.Controllers
{
    [Area("UserSpecific"), Authorize(Roles = SD.Role_User_Vendor)]
    public class VendorsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public VendorsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult VendorDashboard()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var stats = new UserStatsVM()
            {
                registrations = _unitOfWork.Contract.GetAll(u => u.VendorId == claim.Value && u.Status == SD.Proposal_Given).Count(),
                bookings = _unitOfWork.Contract.GetAll(u => u.VendorId == claim.Value && u.Status == SD.Proposal_Accepted).Count()
            };
            return View(stats);
        }


        public IActionResult ContractList(string status)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var contractList = _unitOfWork.Contract.GetAll(u => u.VendorId == claim.Value, includeProperties: "Requirement,Requirement.Resort");
            switch (status)
            {
                case "proposalSent":
                    contractList = contractList.Where(u => u.Status == SD.Proposal_Given);
                    break;
                case "proposalApproved":
                    contractList = contractList.Where(u => u.Status == SD.Proposal_Accepted);
                    break;
                case "completed":
                    contractList = contractList.Where(u => u.Status == SD.Contract_Completed);
                    break;
                default:
                    break;
            }
            return View(contractList);
        }

        public IActionResult ContractDetails(int? contractId)
        {
            if (contractId == null)
            {
                return NotFound();
            }
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var contract = _unitOfWork.Contract.GetFirstOrDefault(u => u.ContractId == contractId && u.VendorId == claim.Value, includeProperties: "Requirement,Requirement.Resort");
            if(contract==null)
            {
                return NotFound();
            }
            return View(contract);
        }


        public IActionResult Feedbacks()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var feedbackList = _unitOfWork.Feedback.GetAll(u => u.forId == claim.Value, includeProperties:"vendor,resort");
            if (feedbackList == null)
            {
                return NotFound();
            }
            return View(feedbackList);
        }
    }
}

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Views/Requirements/Delete.cshtml
@model ExotikaTrial2.Models.Employee

@{
    ViewData["Title"] = "Delete Employee";
}

<div style="padding: 10vh;">
    <div style="padding: 10vh; background-color:rgb(255,255,255); border: 2px solid rgb(0,0,0); border-radius: 12px;">

<h1>Delete Employee</h1>

<h3>Are you sure you want to delete this?</h3>
<br /><br />
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateOfJoining)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfJoining)
        </dd>
    </dl>
    
    <br /><br /><hr /><br /><br />
    <form asp-action="Delete" style="overflow-y: hidden;">
        <input type="hidden" asp-for="EmployeeId" />
        <input type="submit" value="Delete" class="btn1" style="background-color: rgb(255,0,0);"/>
        <a asp-action="Index" class="btn1">Back to List</a>
    </form>
</div>
</div>
</div>

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Views/Requirements/Details.cshtml
@using ExotikaTrial2.Utility
@model ExotikaTrial2.Models.Requirement

@{
    ViewData["Title"] = "Requirements Details";
}


<div style="padding: 10vh;">
    <div style="padding: 10vh; background-color:rgb(255,255,255); border: 2px solid rgb(0,0,0); border-radius: 12px;">
        <h1>Requirement Details</h1>

        <div>
            <br /><br /><hr /><br><br />
            <div class="row">
                <div class="mb-5">
                    <h2>
                        @Html.DisplayNameFor(model => model.Type)
                    </h2>
                    <p>
                        @Html.DisplayFor(model => model.Type)
                    </p>
                </div>
                <div class="mb-5">
                    <h2>
                        @Html.DisplayNameFor(model => model.Category)
                    </h2>
                    <p>
                        @Html.DisplayFor(model => model.Category)
                    </p>
                </div>
                <div class="mb-5">
                    <h2>
                        @Html.DisplayNameFor(model => model.Description)
                    </h2>
                    <p>
                        @Html.DisplayFor(model => model.Description)
                    </p>
                </div>
                <div class="mb-5">
                    @if (Model.Type == "Service")
                    {
                        <h2>
                            @Html.DisplayNameFor(model => model.Duration)
                        </h2>
                        <p>
                            @Html.DisplayFor(model => model.Duration)
                        </p>
                    }
                    else
                    {
                        <h2>
                            @Html.DisplayNameFor(model => model.Quantity)
                        </h2>
                        <p>
                            @Html.DisplayFor(model => model.Quantity)
                        </p>
                    }
                </div>
                <div class="mb-5">
                    <h2>
                        @Html.DisplayNameFor(model => model.lastUpdated)
                    </h2>
                    <p>
                        @Html.DisplayFor(model => model.lastUpdated)
                    </p>
                </div>
                <div class="mb-5">
                    <h2>
                        @Html.DisplayNameFor(model => model.requiredBy)
                    </h2>
                    <p>
                        @Html.DisplayFor(model => model.requiredBy)
                    </p>
                </div>
                <div class="mb-5">
                    <h2>
                        @Html.DisplayNameFor(model => model.Status)
                    </h2>
                    <p>
                        @Html.DisplayFor(model => model.Status)
                    </p>
                </div>
            </div>
        </div>
        <br /><br /><hr /><br /><br />
        @if (Model.Status == SD.Requirement_Posted)
        {
            <a asp-action="UpsertRequirement" asp-route-requirementId="@Model?.RequirementId" class="btn1">Edit</a>
        }
        <a asp-action="RequirementsList" class="btn1">Back to List</a>
            <a asp-action="ProposalList" asp-route-requirementId="@Model?.RequirementId" class="btn1">View Proposals</a>
    </div>
</div>

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Views/Requirements/OngoingContracts.cshtml
@model IEnumerable<ExotikaTrial2.Models.Contract>

    @{
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/ongoingContracts.css" runat="server" />

    var type = Context.Request.Query["type"];
    var products = "text-primary";
    var services = "text-primary";
    var all = "text-primary";

    switch (type)
    {
        case "products":
            products = "active text-white";
            break;
        case "services":
            services = "active text-white";
            break;
        default:
            all = "active text-white";
            break;
    }
}


<section id="Details">
    <div class="d-flex justify-content-between pt-4">
        <div class="p-2 mb-5">
            <h2 class="text-primary">List of Ongoing Contracts</h2>
        </div>
        <div clas="p-2">
            <ul class="list-group list-group-horizontal-sm">
                <a style="text-decoration:none" asp-area="UserSpecific" asp-controller="Requirements" asp-action="OngoingContracts" asp-route-type="products">
                <li class="list-group-item @products">Products</li>
                </a>
                <a style="text-decoration:none" asp-area="UserSpecific" asp-controller="Requirements" asp-action="OngoingContracts" asp-route-type="services">
                <li class="list-group-item @services">Services</li>
                </a>
                <a style="text-decoration:none" asp-area="UserSpecific" asp-controller="Requirements" asp-action="OngoingContracts" asp-route-type="all">
                <li class="list-group-item @all">All</li>
                </a>
            </ul>
        </div>
    </div>
    @if (Model.Count() == 0)
    {
        <p>No Ongoing Contracts in the given category</p>
    }
    else
    {
        @foreach (var contract in Model)
        {
            <div>
                @*<img src="~/Images/stationery.jpg" />*@
                <div class="content row" style="border: 2px solid rgb(0,0,0); border-radius: 12px">
                    <h2>@contract.Vendor.Name</h2><br>
                    <p>@contract.Vendor.StreetAddress, @contract.Vendor.City, @contract.Vendor.State - @contract.Vendor.PostalCode</p>
                    <h3>Phone: @contract.Vendor.PhoneNumber</h3>
                    <h3>Email: @contract.Vendor.emailAddr</h3><br>
                    <p class="mb-3">In effect from @contract.StartDate.ToLongDateString() to @contract.EndDate.ToLongDateString()</p>
                    @*<a href="" class="button">Request Contract Extension</a>*@
                    <a asp-area="UserSpecific" asp-controller="Requirement" asp-action="ProposalDetails" asp-route-requirementId="@contract.RequirementId" class="btn1 mx-1 my-2" style="width:auto">View Contract Details</a>
                    <a asp-area="UserSpecific" asp-controller="Resorts" asp-action="UpsertFeedback" asp-route-forId="@contract.VendorId" class="btn1 mx-1 my-2" style="width:auto">Give/ Edit Feedback</a>
                </div>
            </div>
        }
    }
</section>

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Views/Requirements/ProposalList.cshtml
@model IEnumerable<ExotikaTrial2.Models.Contract>
@{
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />
}

<section id="Details">
    <div class="d-flex justify-content-between pt-4">
        <div class="p-2 mb-5">
            <h2 class="text-primary">Proposal List</h2>
        </div>
    </div>
    <div class="mt-5 mb-5" style="width: 100%">
        <table id="tblData" class="display table table-striped" style="width: 100%; margin-top:5vh">
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Requirement</th>
                    <th>Quantity/Duration</th>
                    <th>Proposed Average Cost</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var contract in Model)
                {
                    <tr>
                        <td>@contract.Vendor.Name, @contract.Vendor.City, @contract.Vendor.State - @contract.Vendor.PostalCode</td>
                        <td>@contract.Requirement.requirementName</td>
                        @if (contract.Requirement.Type == "Product")
                        {
                            <td>@contract.Requirement.Quantity</td>
                        }
                        else
                        {
                            <td>@contract.Requirement.Duration Months</td>
                        }
                        <td>@contract.Price</td>
                        <td>@contract.StartDate.ToLongDateString()</td>
                        <td>@contract.EndDate.ToLongDateString()</td>
                        <td>
                            <a asp-area="UserSpecific" asp-controller="Requirements" asp-action="ProposalDetails" asp-route-contractId="@contract.ContractId" style="display:block">View Details</a>
                            @*<a asp-area="UserSpecific" asp-controller="Vendors" asp-action="Delete" asp-route-forID="@contract.RequirementId">Delete Requirement</a>*@
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
        <a asp-action="RequirementsList" class="btn1">Back to Requirements List</a>
</section>



@section Scripts {

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script>
    $('#tblData').DataTable();
</script>
}