ExotikaTrial2/ExotikaTrial2/Areas/Base/Controllers/BasePagesController.cs
using ExotikaTrial2.DataAccess.Repository.IRepository;
using ExotikaTrial2.Models;
using ExotikaTrial2.Models.ViewModels;
using ExotikaTrial2.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using System.Security.Claims;

namespace ExotikaTrial2.Controllers
{
    [Area("Base")]
    public class BasePagesController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        public BasePagesController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ResortHome()
        {
            return View();
        }

        public IActionResult HandicraftDealerHome()
        {
            return View();
        }

        public IActionResult ResortDetails(string? resortId)
        {
            if (resortId != null)
            {
                ResortDetailsVM resortData = new ResortDetailsVM
                {
                    resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == resortId),
                    packages = _unitOfWork.Package.GetAll(u => u.ResortId == resortId)
                };

                return View(resortData);
            }
            return NotFound();
        }

        public IActionResult ResortsList()
        {
            var resorts = _unitOfWork.Resort.GetAll();
            var handicrafts = _unitOfWork.Product.GetAll(includeProperties: "HandicraftDealer");
            var data = new TouristHomeVM()
            {
                Resorts = resorts,
                Products = handicrafts
            };
            return View(data);
        }

        public IActionResult VendorHome()
        {
            var contracts = _unitOfWork.Requirement.GetAll(u => u.Status == SD.Requirement_Posted, includeProperties: "Resort");
            return View(contracts);
        }

        public IActionResult Book(int? packageId)
        {
            if (packageId == null)
            {
                return NotFound();
            }
            var resId = _unitOfWork.Package.GetFirstOrDefault(u => u.PackageId == packageId).ResortId;
            var res = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == resId);
            var pkg = _unitOfWork.Package.GetFirstOrDefault(u => u.PackageId == packageId);
            var pkgBook = new Booking()
            {
                PackageId = packageId,
                ResortId = resId,
                Resort = res,
                Package = pkg
            };
            return View(pkgBook);
        }

        public IActionResult Proposal(int? requirementId)
        {
            if (requirementId == null)
            {
                return NotFound();
            }
            var resId = _unitOfWork.Requirement.GetFirstOrDefault(u => u.RequirementId == requirementId).ResortId;
            var res = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == resId);
            var req = _unitOfWork.Requirement.GetFirstOrDefault(u => u.RequirementId == requirementId);
            var contProposal = new Contract()
            {
                RequirementId = (int)requirementId,
                //ResortId = resId,
                //Resort = res,
                Requirement = req
            };
            return View(contProposal);
        }


        [HttpPost]
        [Authorize(Roles = SD.Role_User_Vendor)]
        [ValidateAntiForgeryToken]
        public IActionResult Proposal(Contract newContract, IFormFile file)
        {
            if (!User.IsInRole(SD.Role_User_Vendor))
            {
                TempData["Error"] = "Please Login to your account to continue";
            }
            if (ModelState.IsValid && User.IsInRole(SD.Role_User_Vendor))
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"proposalFiles");
                    var extension = Path.GetExtension(file.FileName);
                    using (var fileStreams = new FileStream(Path.Combine(uploads, filename + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    newContract.ProposalFile = @"\proposalFiles\" + filename + extension;
                }
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                newContract.VendorId = claim.Value;
                newContract.Vendor = _unitOfWork.Vendor.GetFirstOrDefault(u => u.VendorId == claim.Value);
                newContract.Requirement = _unitOfWork.Requirement.GetFirstOrDefault(u => u.RequirementId == newContract.RequirementId);
                newContract.CreateDate = DateTime.Now;
                newContract.Status = SD.Proposal_Given;
                newContract.Requirement.Status = SD.Requirement_ProposalsReceived;
                _unitOfWork.Contract.Add(newContract);
                _unitOfWork.Save();
                TempData["Success"] = "Proposal sent successfully";
                return RedirectToAction(nameof(VendorHome));
            }
            TempData["Error"] = "An error occured. Please try later!";
            return View(newContract);
        }


        [HttpPost]
        [ActionName("Book")]
        [Authorize(Roles = SD.Role_User_Tourist)]
        [ValidateAntiForgeryToken]
        public IActionResult Book(Booking newBooking)
        {
            if (!User.IsInRole(SD.Role_User_Tourist))
            {
                TempData["Error"] = "Please Login to your tourist account to continue";
            }
            if (ModelState.IsValid && User.IsInRole(SD.Role_User_Tourist))
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                newBooking.TouristId = claim.Value;
                newBooking.TouristDetails = _unitOfWork.Tourist.GetFirstOrDefault(u => u.TouristId == newBooking.TouristId);
                newBooking.Resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == newBooking.ResortId);
                newBooking.Package = _unitOfWork.Package.GetFirstOrDefault(u => u.PackageId == newBooking.PackageId);
                int duration = (newBooking.CheckOutDate.Date - newBooking.CheckInDate.Date).Days;
                newBooking.TotalPrice = (newBooking.Package.Price * newBooking.noOfBookings * duration);
                _unitOfWork.Bookings.Add(newBooking);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Book_Summary), new { bookingId = newBooking.BookingID });
            }
            return View(newBooking);
        }


        [Authorize(Roles = SD.Role_User_Tourist)]
        public IActionResult Book_Summary(int? bookingId)
        {
            Booking book = _unitOfWork.Bookings.GetFirstOrDefault(u => u.BookingID == bookingId, includeProperties: "Package,Resort,TouristDetails");
            return View(book);
        }


        [HttpPost]
        [ActionName("Book_Summary")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = SD.Role_User_Tourist)]
        public IActionResult Book_Payment(int? bookingId)
        {
            if (!User.IsInRole(SD.Role_User_Tourist))
            {
                TempData["Error"] = "Please Login to your account to continue";
            }
            Booking book = _unitOfWork.Bookings.GetFirstOrDefault(u => u.BookingID == bookingId, includeProperties: "Package,Resort,TouristDetails");
            ResortBookings bookFinal = new()
            {
                PackageId = book.PackageId,
                Package = book.Package,
                ResortId = book.ResortId,
                Resort = book.Resort,
                TouristId = book.ResortId,
                TouristDetails = book.TouristDetails,
                TotalPrice = book.TotalPrice,
                idType = book.idType,
                idNumber = book.idNumber,
                CheckInDate = book.CheckInDate,
                CheckOutDate = book.CheckOutDate,
                noOfBookings = book.noOfBookings,
                CreateDate = DateTime.Now

            };
            int duration = (bookFinal.CheckOutDate.Date - bookFinal.CheckInDate.Date).Days;
            // Stripe Settings
            var domain = "https://localhost:44378/";
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>
                    {
                        new SessionLineItemOptions
                            {
                                PriceData = new SessionLineItemPriceDataOptions
                                    {
                                        UnitAmount = (long)book.TotalPrice*100,
                                        Currency = "inr",
                                        ProductData = new SessionLineItemPriceDataProductDataOptions
                                            {
                                                Name = bookFinal.Package.Name,
                                            },
                                    },
                                Quantity = 1,
                            },
                    },
                Mode = "payment",
                SuccessUrl = domain + $"Base/BasePages/PaymentConfirmation?bookingId={bookFinal.BookingID}",
                CancelUrl = domain + $"Base/BasePages/Book_Summary?bookingId={bookFinal.BookingID}",
            };

            var service = new SessionService();

ExotikaTrial2/ExotikaTrial2/Areas/UserSpecific/Controllers/TouristsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExotikaTrial2.Data;
using ExotikaTrial2.DataAccess.Repository.IRepository;
using ExotikaTrial2.Models;
using System.Security.Claims;

namespace ExotikaTrial2.Controllers
{
    [Area("UserSpecific")]
    public class TouristsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TouristsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Tourists
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userDetails = _unitOfWork.Tourist.GetFirstOrDefault(u => u.TouristId == claim.Value);
            return View(userDetails);
        }

        public IActionResult BookingHistory()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var list = _unitOfWork.ResortBooking.GetAll(u => u.TouristId == claim.Value, includeProperties: "Package,Resort,TouristDetails");
            return View(list);
        }

        public IActionResult BookingDetail(int? bookingId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var detail = _unitOfWork.ResortBooking.GetFirstOrDefault(u => u.BookingID == bookingId && u.TouristId == claim.Value, includeProperties: "Package,Resort,TouristDetails");
            return View(detail);
        }

        public IActionResult UpsertFeedback(string? forId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var fbk = _unitOfWork.Feedback.GetFirstOrDefault(u => u.forId == forId && u.byId == claim.Value, includeProperties: "tourist,resort");
            Feedback feedback = new();
            if (fbk == null)
            {
                feedback.forId = forId;
                feedback.byId = claim.Value;
                feedback.resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == forId);
                feedback.tourist = _unitOfWork.Tourist.GetFirstOrDefault(u => u.TouristId == claim.Value);
                return View(feedback);
            }
            else return View(fbk);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpsertFeedback(Feedback feedback)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (ModelState.IsValid)
            {
                if (feedback.Id == 0)
                {
                    feedback.lastUpdated = DateTime.Now;
                    feedback.resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == feedback.forId);
                    feedback.tourist = _unitOfWork.Tourist.GetFirstOrDefault(u => u.TouristId == feedback.byId);
                    _unitOfWork.Feedback.Add(feedback);
                    _unitOfWork.Save();
                    TempData["Success"] = "Feedback Posted Successfully!";
                }
                else
                {
                    if (feedback.byId == claim.Value)
                    {
                        feedback.lastUpdated = DateTime.Now;
                        feedback.resort = _unitOfWork.Resort.GetFirstOrDefault(u => u.ResortId == feedback.forId);
                        feedback.tourist = _unitOfWork.Tourist.GetFirstOrDefault(u => u.TouristId == feedback.byId);
                        _unitOfWork.Feedback.Update(feedback);
                        _unitOfWork.Save();
                        TempData["Success"] = "Feedback Updated Successfully!";
                    }
                }
                return RedirectToAction("BookingHistory");   //return RedirectToAction("Index", "ControllerName"); if we want to go to some other controller
            }
            TempData["Error"] = "An error occured. Please try later.";
            return View(feedback);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var bookingList = _unitOfWork.ResortBooking.GetAll(u=>u.TouristId==claim.Value, includeProperties: "Package,Resort,TouristDetails");
            return Json(new { data = bookingList });
        }
        #endregion
    }
}

ExotikaTrial2/ExotikaTrial2/Areas/Base/Views/BasePages/HandicraftDealerHome.cshtml
@{
	Layout = "_Layout";
    <link rel="stylesheet" href="~/css/handicraftDealerHome.css" runat="server"/>
} 


<br><br><br><br>

			<div>
				<img src="~/images/handicraft.jfif"  width="30%" height="30%" >
				<p>Are you a handicraft dealer looking forward to increase the outreach of your beautifully handcrafted products by expanding your presence online? Well... Exotika is exactly what you are looking for!<p>
				<p>We all know tourists look for some momentos to take away as a memory of their visit, or as a gift to their loved ones. For this purpose, they often turn to the specialities of their place of visit - the local handicrafts.</p>
				<p>By registering your business with us, you can list out the region-specific handicrafts that you provide, along with your business details like name, address and contact information. This would help the tourists reach out to you in an easy manner, helping expand your outreach and sales. What's more? You get all this for FREE!</p>
				<p>Through the local handicraft dealers portal, a user can list out the region-specific handicrafts they provide, along with their business details, including address and contact information.</p>
				<span><b>So what are you waiting for?</b></span><br>
				<a href="SignIn.html" class="GoToPortalBtn" style="font-size: 150%"><span><b>Register Now!</b></span></a>
			</div>

ExotikaTrial2/ExotikaTrial2/Areas/Base/Views/BasePages/PaymentConfirmation.cshtml
@model ExotikaTrial2.Models.ResortBookings
@{
    <link rel="stylesheet" href="~/css/bootswatch.css" runat="server"/>
    <link rel="stylesheet" href="~/css/bootswatch.css" runat="server"/>
    <link rel="stylesheet" href="~/css/FormCSS.css" runat="server"/>
}


<h1 class="text-primary text-center pt-5">Payment Successful!</h1>

<div class="container row m-5">
    <div class="col-sm-12 col-md-6 text-center pt-4">
        <h2>Booking Details for @Model.TouristDetails.Name: @Model.Package.Name</h2><br />
        at <h3>@Model.Resort.Name, @Model.Resort.City, @Model.Resort.State - @Model.Resort.PostalCode</h3> <br /><br />
        <p><b>Check-In</b> @Model.CheckInDate.ToLongDateString()</p>
        <p><b>Check-Out</b> @Model.CheckOutDate.ToLongDateString()</p>
        <p><b>Booking for:</b> @Model.noOfBookings, &nbsp; <b>Total:</b> Rs. @Model.TotalPrice</p>
    </div>
    <div class="col-sm-12 col-md-6 text-center pt-4" style="color:maroon">
        <br />
        <p style="font-size:120%">Your payment has been completed successfully, and the booking has been confirmed! You will be receiving a confirmation email shortly. Safe Travels!</p> <br />
        <img src="~/images/ThankYou.jfif" width="80%" /><br /><br />
        <a asp-area="UserSpecific" asp-controller="Tourists" asp-action="BookingDetail" asp-route-bookingId="@Model.BookingID" class="btn1 mt-2">Go to User Dashboard</a>
    </div>
</div>

ExotikaTrial2/ExotikaTrial2/Areas/Base/Views/BasePages/Proposal.cshtml
@using ExotikaTrial2.Utility
@model ExotikaTrial2.Models.Contract
@{
    Layout = "_Layout";
    <link rel="stylesheet" href="~/css/vendorHome.css" runat="server" />
}

<div style="padding: 10vh;">
    <div style="padding: 10vh; background-color:rgb(255,255,255); border: 2px solid rgb(0,0,0); border-radius: 12px">
        <h1>Requirement Details</h1>

        <div class="mb-5">
            <hr /><br><br />
            <div class="row">
                <div class="mb-3">
                    <h2>@Html.DisplayNameFor(model => model.Requirement.Resort.Name)</h2>
                    <p>@Html.DisplayFor(model => model.Requirement.Resort.Name), @Html.DisplayFor(model => model.Requirement.Resort.City), @Html.DisplayFor(model => model.Requirement.Resort.State) - @Html.DisplayFor(model => model.Requirement.Resort.PostalCode)</p>
                </div>
                <div class="mb-3">
                    <h2>@Html.DisplayNameFor(model => model.Requirement.Type)</h2>
                    <p>@Html.DisplayFor(model => model.Requirement.Type)</p>
                </div>
                <div class="mb-3">
                    <h2>@Html.DisplayNameFor(model => model.Requirement.Category)</h2>
                    <p>@Html.DisplayFor(model => model.Requirement.Category)</p>
                </div>
                <div class="mb-3">
                    <h2>@Html.DisplayNameFor(model => model.Requirement.requirementName)</h2>
                    <p>@Html.DisplayFor(model => model.Requirement.requirementName)</p>
                </div>
                <div class="mb-3">
                    <h2>@Html.DisplayNameFor(model => model.Requirement.Description)</h2>
                    <p>@Html.DisplayFor(model => model.Requirement.Description)</p>
                </div>
                @if (Model.Requirement.Type == "Service")
                {
                    <div class="mb-3">
                        <h2>@Html.DisplayNameFor(model => model.Requirement.Duration)</h2>
                        <p>@Html.DisplayFor(model => model.Requirement.Duration)</p>
                    </div>
                }
                else
                {
                    <div class="mb-3">
                        <h2>@Html.DisplayNameFor(model => model.Requirement.Quantity)</h2>
                        <p>@Html.DisplayFor(model => model.Requirement.Quantity)</p>
                    </div>
                }
                <div class="mb-3">
                    <h2>@Html.DisplayNameFor(model => model.Requirement.lastUpdated)</h2>
                    <p>@Html.DisplayFor(model => model.Requirement.lastUpdated)</p>
                </div>
                <div class="mb-3">
                    <h2>@Html.DisplayNameFor(model => model.Requirement.requiredBy)</h2>
                    <p>@Html.DisplayFor(model => model.Requirement.requiredBy)</p>
                </div>
                <br /><br /><hr /><br /><br />
                <a asp-action="RequirementsList" class="button" style="width:auto">Back to Vendor Home</a>
                <a href="#Propose" class="button" style="width:auto">Give Proposal</a>
            </div>
        </div>
    </div>
</div>



<div style="padding: 10vh;" id="Propose">
    <div style="padding: 10vh; background-color:rgb(255,255,255); border: 2px solid rgb(0,0,0); border-radius: 12px;">
        <h1>Submit Proposal</h1>

        <hr />
        <div class="row">
            <div class="col-12">
                <form method="post" asp-action="Proposal" enctype="multipart/form-data">
                    <input asp-for="RequirementId" type="hidden" />
                    <div class="row col-12 mt-5">
                        @if (Model.Requirement.Type == "Product")
                        {
                            <p>Expected Delivery of Product</p>
                        }
                        else
                        {
                            <p>Proposed start and end dates of the package</p>
                        }
                        <div class="form-floating py-2 col-6 mb-3">
                            <input asp-for="StartDate" class="form-control" />
                            <label asp-for="StartDate" class="control-label"></label>
                            <span asp-validation-for="StartDate" class="text-danger"></span>
                        </div>
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-floating py-2 col-6 mb-3">
                            <input asp-for="EndDate" min="1" class="form-control" />
                            <label asp-for="EndDate" class="control-label"></label>
                            <span asp-validation-for="EndDate" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12 mb-3">
                            <textarea asp-for="Summary" class="form-control" rows="3"></textarea>
                            <label asp-for="Summary" class="control-label"></label>
                            <span asp-validation-for="Summary" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-6 mb-3">
                            <input asp-for="Price" class="form-control" />
                            @if (Model.Requirement.Type == "Product")
                            {
                                <label asp-for="Price" class="control-label">Price per unit</label>
                            }
                            else
                            {
                                <label asp-for="Price" class="control-label">Per month cost</label>
                            }
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-6 mb-3">
                            <input type="file" name="file" asp-for="ProposalFile" class="form-control" />
                            <label asp-for="ProposalFile" class="control-label"></label>
                            <span asp-validation-for="ProposalFile" class="text-danger"></span>
                        </div>
                    </div>
                    <br /><br />
                    <div class="form-floating">
                        <button type="submit" class="btn1" onclick="return ValidateInput()">Create</button>
                    </div>
                </form>
            </div>
        </div>
        <br /><br /><hr /><br /><br />
        <a asp-area="UserSpecific" asp-controller="BasePages" asp-action="VendorHome" class="btn1">Back to Vendor Home</a>
    </div>
</div>






@section Scripts{
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<partial name="_ValidationScriptsPartial" />
<script>
    $(document).ready(function() {
        var date = new Date().toISOString().slice(0,10);
        console.log(date);
        $('#StartDate').attr('value',date);
        $('#StartDate').attr('min',date);
        $('#EndDate').attr('value',date);
        $('#EndDate').attr('min',date);
    });
</script>
<script>
    function CheckDate() {
        var d1 = new Date(document.getElementById("StartDate").value);
        var d2 = new Date(document.getElementById("EndDate").value);
        console.log(d1);
        console.log(d2);
            if (d1.getTime() > d2.getTime()) {
                Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: 'End date of the contract must fall after its start date. Please check the dates!',
            })
            document.getElementById("EndDate").value = "";
            return false;
        }
        return true;
    }
</script>
}

ExotikaTrial2/ExotikaTrial2/Areas/Base/Views/BasePages/VendorHome.cshtml
@model IEnumerable<ExotikaTrial2.Models.Requirement>
@{
    Layout = "_Layout";
    <link rel="stylesheet" href="~/css/vendorHome.css" runat="server" />

}
<p style="font-size:145%;">Search for a city to view in and nearby resorts, attractions, local handicrafts and fairs/festivals.</p>
<br>
<form>
    <label for="stateSelect">States and UTs:</label>
    <select name="state" id="stateSelect" onchange="makeSubmenu(this.value)" style="width:92.5%;">
        <option value="" disabled selected>Choose State</option>
        <option value="andaman_and_nicobar">Andaman and Nicobar Islands</option>
        <option value="andhra_pradesh">Andhra Pradesh</option>
        <option value="arunanchal_pradesh">Arunanchal Pradesh</option>
        <option value="assam">Assam</option>
        <option value="bihar">Bihar</option>
        <option value="chandigarh">Chandigarh</option>
        <option value="chhattisgarh">Chhattisgarh</option>
        <option value="dadra_nagar_haveli">Dadra and Nagar Haveli and Daman and Diu</option>
        <option value="delhi">Delhi</option>
        <option value="goa">Goa</option>
        <option value="gujrat">Gujrat</option>
        <option value="haryana">Haryana</option>
        <option value="himachal_pradesh">Himachal Pradesh</option>
        <option value="jammu_and_kashmir">Jammu and Kashmir</option>
        <option value="jharkhand">Jharkhand</option>
        <option value="karnataka">Karnataka</option>
        <option value="kerala">Kerala</option>
        <option value="ladakh">Ladakh</option>
        <option value="lakshadweep">Lakshadweep</option>
        <option value="madhya_pradesh">Madhya Pradesh</option>
        <option value="maharashtra">Maharashtra</option>
        <option value="manipur">Manipur</option>
        <option value="meghalaya">Meghalaya</option>
        <option value="mizoram">Mizoram</option>
        <option value="nagaland">Nagaland</option>
        <option value="odisha">Odisha</option>
        <option value="puducherry">Puducherry</option>
        <option value="punjab">Punjab</option>
        <option value="rajasthan">Rajasthan</option>
        <option value="sikkim">Sikkim</option>
        <option value="tamil_nadu">Tamil Nadu</option>
        <option value="telangana">Telangana</option>
        <option value="tripura">Tripura</option>
        <option value="uttarakhand">Uttarakhand</option>
        <option value="uttar_pradesh">Uttar Pradesh</option>
        <option value="west_bengal">West Bengal</option>
    </select>
    <br><br>
    <label for="citySelect">City:</label>
    <select id="citySelect" size="1" name="city" style="width:92.5%;">
        <option value="" disabled selected>Choose City</option>
    </select>
    <br><br>
    <input style="margin-left: 20px;" type="submit" value="Search">
</form>
<br>
<br>
<br>
<br>

<section id="Details">
    @foreach (var requirement in Model)
    {
        <div class="@requirement.Type @requirement.Category content-box">
            <img src="~/Images/stationery.jpg" />
            <div class="content-req">
                <h2>@requirement.Resort.Name</h2><br>
                <p>@requirement.Resort.City, @requirement.Resort.State - @requirement.Resort.PostalCode</p>
                <h3>Phone: @requirement.Resort.PhoneNumber</h3>
                <h3>Email: @requirement.Resort.emailAddr</h3><br>
                @if (requirement.Type == "Product")
                {
                    <p>@requirement.requirementName x @requirement.Quantity Required by @requirement.requiredBy.ToLongDateString()</p>
                }
                else
                {
                    <p>@requirement.Category, Required by @requirement.requiredBy.ToLongDateString()</p>
                }
                <a asp-controller="BasePages" asp-controller="Base" asp-action="Proposal" asp-route-requirementId="@requirement.RequirementId" class="button mt-5">Give Proposal</a>
            </div>
        </div>
    }



    @section Scripts{
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    }